name: Build and Deploy
on:
  push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1

    - name: Build and deploy to storybook-static branch
      uses: JamesIves/github-pages-deploy-action@2.0.3
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: storybook-static
        FOLDER: storybook-static
        BUILD_SCRIPT: npm install && npm run build-storybook
